
on:
  push:
    branches: 
      - main
jobs:
  Make:
    runs-on: ubuntu-latest
    name: Make ${{matrix.work}} ${{matrix.arch}}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: down
        uses: MitchWind/ftp-deploy@master
        with:
            server: ${{ secrets.FTP_HOST }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWOD }}
            local_dir: 
            server_dir: public_html/furlanseletrica.com.br
